<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQk5L3Pc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQk5L3Pc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQk5L3Pc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQk5L3Pc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQk5L3Pc\App_KernelDevDebugContainer([
    'container.build_hash' => 'Qk5L3Pc',
    'container.build_id' => '5ba31a7e',
    'container.build_time' => 1684263199,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQk5L3Pc');
